export const productCarouselConfig = [
	{
		id: "4",
		name: "Super Morning",
		description: "Kickstart your day with our ultimate morning pill:ignite your energy, shield your skin from UV rays, and conquer the day with unparalleled drive. Ditch the energy drinks-this is your shortcut to peak performance, boundless stamina, and stress-free, exhilarating starts to every day.",
		imageUrl: "/carousel/Morning.webp",
		price: 39.99,
		category: "Morning",
		productUrl: "/products/super-morning",
		ingredients: ["Vitamin D", "Zinc", "Elderberry", "Echinacea"],
	},
	{
		id: "2",
		name: "Super Immune",
		imageUrl: "/carousel/Immune.webp",
		description: "Step into any crowd with Super Immune and stay shielded from illness. Harness the extraordinary power of nature’s most potent plants to fortify your defenses and enjoy unparalleled health. With Super Immune, you’re not just protected-you’re empowered to thrive in any environment.",
		price: 34.99,
		category: "Immune",
		productUrl: "/products/super-immune",
		ingredients: ["Vitamin D", "Zinc", "Elderberry", "Echinacea"],
	},
	{
		id: "3",
		name: "Super Sleep",
		imageUrl: "/carousel/Sleep.webp",
		description: "Achieve deep, rejuvenating sleep with our powerful pill: unwind effortlessly, rediscover your dreams, and wake up feeling revitalized. Infused with proven, ancient ingredients for quicker, more effective relaxation.",
		price: 29.99,
		category: "Sleep",
		productUrl: "/products/super-sleep",
		ingredients: ["Melatonin", "Valerian Root", "Vitamin B6", "Magnesium"],
	},
	{
		id: "1",
		name: "Super Brain",
		imageUrl: "/carousel/Brain.webp",
		description: "Imagine stepping into a meeting, fully in control and outshining the competition. Super Brain ensures you stay alert and focused, enhances your mental clarity, and speeds up your learning. Embrace the confidence and cognitive agility that keep you on top of the game and drive your success to new heights.",
		price: 39.99,
		category: "Brain",
		productUrl: "/products/super-brain",
		ingredients: ["Ginkgo Biloba", "Bacopa", "Lion's Mane", "Phosphatidylserine"],
	},
];
